name: Comment on PR and Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest
    container:
      image: stalchmst/zrb:1.16.2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Run zrb code-review and post comment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          set -e
          echo "Running code review for PR from $GITHUB_HEAD_REF to $GITHUB_BASE_REF..."
          REVIEW_COMMENT=$(zrb code-review --source "$GITHUB_HEAD_REF" --target "$GITHUB_BASE_REF")
          zrb submit-comment --comment "$REVIEW_COMMENT"
