name: Comment on PR

on:
  pull_request:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo, number } = context.issue;
            const tag = "${{steps.get_tag.outputs.tag}}";
            github.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: `Current commit tag: ${tag}`
            });